version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - mvn install -DskipTests=true
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
