phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - cd /codebuild/output/src4080305061/src  # Gradle 빌드 파일이 있는 디렉토리로 이동
      - gradle build  # Gradle 빌드 실행
artifacts:
  files:
    - build/libs/*.jar  # 빌드 결과물을 아티팩트로 지정

